[http.routers.traefik]
    rule="PathPrefix(`/`)"
    service="api@internal"
    entryPoints=["traefik"]
    middlewares=["auth"]

[http.routers.metrics]
    rule="PathPrefix(`/metrics`)"
    service="prometheus@internal"
    entryPoints=["metrics"]

[http.middlewares.auth.basicAuth]
    usersFile = "/run/secrets/traefik_htpasswd"
