# internal traefik api and dashboard router (http, for homepage widget)
[http.routers.traefik]
    rule="Path(`/traefik`) || PathPrefix(`/traefik/`)"
    service="api@internal"
    entryPoints=["traefik"]

[http.routers.metrics]
    rule="PathPrefix(`/metrics`)"
    service="prometheus@internal"
    entryPoints=["metrics"]

[http.middlewares.auth.basicAuth]
    usersFile = "/run/secrets/traefik_auth_users"
    removeHeader = true
    headerField = "X-Auth-User"

[http.middlewares.internal.ipAllowList]
    sourceRange = ["172.20.0.0/23"]
