[http.routers.metrics]
    rule="PathPrefix(`/metrics`)"
    service="prometheus@internal"
    entryPoints=["metrics"]

[http.middlewares.auth.basicAuth]
    usersFile = "/run/secrets/traefik_auth_users"

[http.middlewares.internal.ipAllowList]
    sourceRange = ["172.20.0.0/23"]
