version: "3.7"

services:
  traefik:
    build: ./traefik
    init: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt/live/:/etc/letsencrypt/live/:ro
      - /etc/letsencrypt/archive/:/etc/letsencrypt/archive/:ro
      - ./log/traefik/:/var/log/traefik/
  limbo:
    build: ./limbo
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.limbo-http.rule=PathPrefix(`/`)"
      - "traefik.http.routers.limbo-http.priority=1"
      - "traefik.http.routers.limbo-https.rule=PathPrefix(`/`)"
      - "traefik.http.routers.limbo-https.priority=1"
      - "traefik.http.routers.limbo-https.tls"
  prometheus:
    image: prom/prometheus:v2.37.8
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=/prometheus
    web-conductor:
      path: /prometheus
      admin: true
  prometheus-node-exporter:
    image: prom/node-exporter:v1.5.0
  grafana:
    image: grafana/grafana:9.5.1
    volumes:
      - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./configs/grafana/provisioning:/etc/grafana/provisioning:ro
    web-conductor:
      path: /grafana
      admin: true

volumes:
  prometheus-data:
