version: "3.7"

services:
  traefik:
    build: ./traefik
    init: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./log/traefik/:/var/log/traefik/
  limbo:
    build: ./limbo
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.limbo-http.rule=PathPrefix(`/`)"
      - "traefik.http.routers.limbo-http.priority=1"
      - "traefik.http.routers.limbo-https.rule=PathPrefix(`/`)"
      - "traefik.http.routers.limbo-https.priority=1"
      - "traefik.http.routers.limbo-https.tls"
