- name: Install web-conductor
  hosts: all

  tasks:
  - name: Install pipx
    ansible.builtin.apt:
      name: pipx
      cache_valid_time: 3600
    become: true

  - name: Copy files
    ansible.posix.synchronize:
      src: files/
      dest: "{{ wc_dir }}/"

  - name: Check user files
    ansible.builtin.stat:
      path: "user/"
    register: stat_user
    delegate_to: localhost

  - name: Copy user files
    ansible.posix.synchronize:
      src: user/
      dest: "{{ wc_dir }}/"
    when: stat_user.stat.isdir | default(false)

  - name: Create secrets directory
    ansible.builtin.file:
      path: "{{ wc_dir }}/secrets"
      state: directory
      mode: '0700'

  - name: Create htpasswd secret
    ansible.builtin.copy:
      dest: "{{ wc_dir }}/secrets/traefik_htpasswd"
      mode: '0600'
      content: |
        {% for user in wc_auth_users %}
        {{ user }}
        {% endfor %}

  - name: Create configuration files
    ansible.builtin.command:
      chdir: "{{ wc_dir }}"
      argv: ['./web-conductor.py', 'config']
    register: shell_result
    changed_when: shell_result.stdout | length > 0

  - name: Start services
    ansible.builtin.command:
      chdir: "{{ wc_dir }}"
      argv: ['./fetch.sh']
    register: shell_result
    changed_when: shell_result.stdout | length > 0
    when: wc_start
