- name: Install rsync,pipx
  ansible.builtin.apt:
    name: rsync,pipx
    cache_valid_time: 3600
  become: true

- name: Include sync tasks
  ansible.builtin.include_tasks:
    file: include/sync.yml
  loop:
    - name: core
      src: "{{ role_path }}/files"
      dest: "{{ wc_dir }}"
    - name: user
      src: "{{ wc_user_dir }}"
      dest: "{{ wc_dir }}/user"
  loop_control:
    loop_var: sync_args
    label: "{{ sync_args.name }}"

- name: Create configuration files
  ansible.builtin.command:
    chdir: "{{ wc_dir }}"
    argv: ['./web-conductor.py', 'run', 'config']
  register: shell_result
  changed_when: shell_result.stdout | length > 0

- name: Update workspace files
  ansible.builtin.command:
    chdir: "{{ wc_dir }}"
    argv: ['./web-conductor.py', 'run', 'update']
  register: shell_result
  changed_when: shell_result.stdout | length > 0

- name: "Run docker compose (state: {{ wc_compose_state }}, build: {{ wc_compose_build }}, pull: {{ wc_compose_pull }})"
  community.docker.docker_compose_v2:
    project_src: "{{ wc_dir }}"
    remove_orphans: true
    state: "{{ wc_compose_state }}"
    build: "{{ wc_compose_build }}"
    pull: "{{ wc_compose_pull }}"

- name: Download grafana dashboards
  ansible.builtin.command:
    chdir: "{{ wc_dir }}"
    argv: "{{ ['./scripts/grafana-dash-down.sh'] + wc_grafana_dashboard_ids }}"
  register: shell_result
  changed_when: shell_result.stdout | length > 0
  when: wc_grafana_dashboard_ids | length > 0 and wc_compose_state != 'absent' and wc_compose_state != 'stopped'
