- name: Include setup tasks
  ansible.builtin.include_tasks:
    file: setup.yml
  when: wc_include_setup

- name: Include sync tasks
  ansible.builtin.include_tasks:
    file: include/sync.yml
  loop:
    - name: core
      src: "{{ role_path }}/files"
      dest: "{{ wc_dir }}"
    - name: user
      src: "{{ wc_user_dir }}"
      dest: "{{ wc_dir }}/user"
  loop_control:
    loop_var: sync_args
    label: "{{ sync_args.name }}"

- name: Setup venv and install packages
  ansible.builtin.pip:
    virtualenv: "{{ wc_dir }}/.venv"
    virtualenv_command: python3 -m venv
    requirements: "{{ wc_dir }}/requirements.txt"
    # XXX: possible ansible.builtin.pip bug...
    # ansible.builtin.pip always reports changes when installing local packages
    # using name, but with a 'requirements.txt' file it detects the changes
    # correctly (same with vcs urls, using 'pip list')
    # https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/pip.py
    # name: "{{ wc_dir }}"
    # editable: true

- name: Setup user profile
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts.user_dir }}/.profile"
    marker: "# {mark} ANSIBLE goncalomb/web-conductor"
    block: |
      export PATH="{{ wc_dir }}/.venv/bin:$PATH"
      cd "{{ wc_dir }}"
  when: wc_setup_user_profile

- name: Create configuration files
  ansible.builtin.command:
    chdir: "{{ wc_dir }}"
    argv: ['./.venv/bin/web-conductor', 'run', 'config']
  register: shell_result
  changed_when: shell_result.stdout | length > 0

- name: Update workspace files
  ansible.builtin.command:
    chdir: "{{ wc_dir }}"
    argv: ['./.venv/bin/web-conductor', 'run', 'update']
  register: shell_result
  changed_when: shell_result.stdout | length > 0

- name: "Run docker compose (state: {{ wc_compose_state }}, build: {{ wc_compose_build }}, pull: {{ wc_compose_pull }})"
  community.docker.docker_compose_v2:
    project_src: "{{ wc_dir }}"
    remove_orphans: true
    state: "{{ wc_compose_state }}"
    build: "{{ wc_compose_build }}"
    pull: "{{ wc_compose_pull }}"
  environment:
    BUILDX_NO_DEFAULT_ATTESTATIONS: "{{ wc_compose_default_attestations | ternary('0', '1') }}"

- name: Download grafana dashboards
  ansible.builtin.command:
    chdir: "{{ wc_dir }}"
    argv: "{{ ['./scripts/grafana-dash-down.sh'] + wc_grafana_dashboard_ids }}"
  register: shell_result
  changed_when: shell_result.stdout | length > 0
  when: wc_grafana_dashboard_ids | length > 0 and wc_compose_state != 'absent' and wc_compose_state != 'stopped'
