- name: Pull WireGuard configuration
  ansible.builtin.synchronize:
    src: /config/
    dest: "{{ wc_pull_dir }}/wireguard-config/"
    mode: pull
    rsync_opts:
      # proxy rsync to the wireguard container (install rsync if not present)
      - --rsync-path="{{ wc_dir }}/scripts/wireguard-rsync.sh"
      - --include=peer*
      - --exclude=*
      - --mkpath
