---
- name: Prepare
  hosts: all

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install python3-requests
      ansible.builtin.apt:
        name: python3-requests
        cache_valid_time: 3600

    - name: Install Docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
        apply:
          become: true
      vars:
        docker_users:
          - "{{ ansible_facts.user_id }}"
        docker_daemon_options:
          userland-proxy: false
          features:
            containerd-snapshotter: false # required for DinD (molecule)

    - name: Install Loki Docker logging driver
      community.docker.docker_plugin:
        plugin_name: grafana/loki-docker-driver:3.7.0-amd64
        alias: loki-docker-driver
        state: enable
