---
- name: Prepare
  hosts: all

  tasks:
    # required for ansible.builtin.apt with cache_valid_time (first run)
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    # required for community.docker.docker_plugin
    - name: Install python3-requests
      ansible.builtin.apt:
        name: python3-requests
        cache_valid_time: 3600

    - name: Include setup tasks
      ansible.builtin.include_role:
        name: goncalomb.web-conductor
        tasks_from: setup
