services:
  traefik:
    build: ./services/traefik
    init: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt/live/:/etc/letsencrypt/live/:ro
      - /etc/letsencrypt/archive/:/etc/letsencrypt/archive/:ro
      - ./log/traefik/:/var/log/traefik/
    secrets:
      - traefik_auth_users
    x-web-conductor:
      route: # hardcoded to api@internal
        path: /
        admin: true

  limbo:
    build: ./services/limbo
    environment:
      - "LIMBO_DEBUG="
    x-web-conductor:
      route:
        path: /
        priority: 1

secrets:
  traefik_auth_users:
    file: ./secrets/traefik_auth_users
