x-web-conductor:
  group: Telemetry

services:
  prometheus:
    image: prom/prometheus:v3
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=/prometheus
    x-web-conductor:
      name: Prometheus
      route:
        path: /prometheus
        admin: true
      homepage:
        icon: prometheus.png
        widget:
          type: prometheus
          url: http://prometheus:9090/prometheus/

  prometheus-node-exporter:
    image: prom/node-exporter:v1
    x-web-conductor:
      homepage: true

  loki:
    image: grafana/loki:3.7.0
    restart: unless-stopped
    ports:
      - 127.0.0.1:3100:3100 # bind to localhost for the logging driver
    volumes:
      - ./configs/loki/config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki

  grafana:
    image: grafana/grafana:13.0
    volumes:
      - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./configs/grafana/provisioning:/etc/grafana/provisioning:ro
    x-web-conductor:
      name: Grafana
      route:
        path: /grafana
        admin: true
      homepage:
        icon: grafana.png
        widget:
          type: grafana
          version: 2
          url: http://grafana:3000/grafana/

volumes:
  prometheus-data:
  loki-data:
