services:
  prometheus:
    image: prom/prometheus:v3
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=/prometheus
    x-web-conductor:
      route:
        path: /prometheus
        admin: true

  prometheus-node-exporter:
    image: prom/node-exporter:v1

  grafana:
    image: grafana/grafana:13.0
    volumes:
      - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./configs/grafana/provisioning:/etc/grafana/provisioning:ro
    x-web-conductor:
      route:
        path: /grafana
        admin: true

volumes:
  prometheus-data:
