x-web-conductor:
  group: Core

services:
  traefik:
    build: ./services/traefik
    init: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt/live/:/etc/letsencrypt/live/:ro
      - /etc/letsencrypt/archive/:/etc/letsencrypt/archive/:ro
      - ./log/traefik/:/var/log/traefik/
    secrets:
      - traefik_auth_users
    networks:
      default:
        ipv4_address: 172.20.0.1
    x-web-conductor:
      name: Traefik
      route: # hardcoded to api@internal
        path: /traefik
        admin: true
      homepage:
        icon: traefik.png
        widget:
          type: traefik
          url: http://traefik:81/traefik/

  limbo:
    build: ./services/limbo
    environment:
      - LIMBO_DEBUG=
      - LIMBO_LOGOUT_REDIRECT=
    x-web-conductor:
      name: Limbo
      description: Fallback service for unknown routes.
      route:
        path: /
        priority: 1
      routes:
        limbo:
          path: /limbo
          admin: true
        logout:
          path: /logout
          admin: true
          auth: false
      homepage:
        href: /limbo
        weight: 999

secrets:
  traefik_auth_users:
    file: ./secrets/traefik_auth_users

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/23
          ip_range: 172.20.1.0/24
          gateway: 172.20.1.254
