x-web-conductor:
  group: Core

services:
  wireguard:
    # https://github.com/linuxserver/docker-wireguard
    image: linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=${WC_WIREGUARD_SERVERURL:?}
      - SERVERPORT=${WC_WIREGUARD_SERVERPORT:?}
      - PEERS=${WC_WIREGUARD_PEERS:?}
      - PEERDNS=auto
      - INTERNAL_SUBNET=${WC_WIREGUARD_INTERNAL_SUBNET:?}
      - ALLOWEDIPS=${WC_WIREGUARD_ALLOWEDIPS:?}
      - PERSISTENTKEEPALIVE_PEERS=all
      - LOG_CONFS=false
    volumes:
      - ./configs/wireguard/coredns:/config/coredns:ro
      - wireguard-config:/config
      - /lib/modules:/lib/modules
    ports:
      - ${WC_WIREGUARD_SERVERPORT:?}:51820/udp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    x-web-conductor:
      name: WireGuard
      homepage:
        icon: wireguard.png

volumes:
  wireguard-config:
