[api]

[metrics.prometheus]
manualRouting = true

[entryPoints.http]
address = ":80"

[entryPoints.http.http.redirections.entryPoint]
to = "https"
scheme = "https"
permanent = false
priority = 1

[entryPoints.https]
address = ":443"
asDefault = true

[entryPoints.https.http.tls]

[entryPoints.metrics]
address = ":82"

[log]
filePath = "/var/log/traefik/traefik.log"
format = "json"
level = "INFO"

[accessLog]
filePath = "/var/log/traefik/access.log"
format = "json"
[accessLog.fields.headers.names]
"User-Agent" = "keep"
"Referer" = "keep"

[providers.docker]
exposedbydefault = false

[providers.file]
directory = "/etc/traefik/dynamic"
