[experimental]
otlpLogs = true

[api]
basepath = "/traefik"

[metrics.prometheus]
manualRouting = true

[entryPoints.http]
address = ":80"

[entryPoints.http.http.redirections.entryPoint]
to = "https"
scheme = "https"
permanent = false
priority = 1

[entryPoints.https]
address = ":443"
asDefault = true

[entryPoints.https.http.tls]

[entryPoints.traefik]
address = ":81"

[entryPoints.metrics]
address = ":82"

[log]
filePath = "/var/log/traefik/traefik.log"
format = "json"
level = "INFO"

# [log.otlp]
# http.endpoint = "http://loki:3100/otlp/v1/logs"

[accessLog]
filePath = "/var/log/traefik/access.log"
format = "json"

[accessLog.fields.headers.names]
"User-Agent" = "keep"
"Referer" = "keep"

[accessLog.otlp]
http.endpoint = "http://loki:3100/otlp/v1/logs"

[providers.docker]
exposedbydefault = false

[providers.file]
directory = "/etc/traefik/dynamic"
