[server]
root_url = /grafana
serve_from_sub_path = true

[auth]
disable_login_form = true

# for homepage widget
# https://gethomepage.dev/widgets/services/grafana/
[auth.basic]
enabled = true

# for vpn users without authentication
[auth.anonymous]
enabled = true
org_name = Main Org.
org_role = Viewer

# for traefik basic authentication
[auth.proxy]
enabled = true
header_name = X-Auth-User
header_property = username

[users]
# https://grafana.com/grafana/dashboards/1860-node-exporter-full/
home_page = /grafana/d/rYdddlPWk
